kafka:
  topic: helloworld.t
  group-id: helloworld.t

  bootstrap-servers: localhost:9092
  security-protocol:
  ssl:
    truststore:
      location:
      password:
    keystore:
      location:
      password:
    keypassword:

dcos:
  entrypoint:

management:
  security:
    enabled: false

monitoring:
  endpoint:
    enabled: true
    path: prometheus

spring.application.name: MsKafka

server:
  port: ${PORT0}
  ssl:
    key-store: ${KAFKA_SSL_KEYSTORE_LOCATION}
    key-store-password: ${KAFKA_SSL_KEYSTORE_PASSWORD}
    key-alias: 1
    trust-store: ${KAFKA_SSL_TRUSTSTORE_LOCATION}
    trust-store-password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD}
    enabled: true
    client-auth: need